apiVersion: v2
name: urlshortener
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: alloy
    version: 1.10.0
    repository: https://grafana.github.io/helm-charts 
  - name: redis-ha
    version: 4.39.0
    repository: https://dandydeveloper.github.io/charts/

