kind: ConfigMap
apiVersion: v1
metadata:
  name: backend-cf
data:
  PGHOST: {{ quote .Values.db.host }}
  PGPASSWORD: {{ quote .Values.db.password }}
  PGUSER: {{ quote .Values.db.user }}
  PGDATABASE: {{ quote .Values.db.database }}
  REDIS_HOST: {{ quote .Values.redis.host }}
  REDIS_PORT: {{ quote .Values.redis.port }}
  REDIS_PASSWORD: {{ quote .Values.redis.password }}
  SESSION_SECRET: {{ quote .Values.session.secret }}
  NODE_ENV: {{ quote .Values.env }}
