apiVersion: v1
kind: ConfigMap
metadata:
  name: alloy-cf
data:
  config.alloy: |-
{{ tpl (.Files.Get "files/backend.alloy") . | indent 4 }}
{{ tpl (.Files.Get "files/db.alloy") . | indent 4 }}
{{ tpl (.Files.Get "files/logs.alloy") . | indent 4 }}
{{ tpl (.Files.Get "files/redis.alloy") . | indent 4 }}